nginx:
 image: nginx
 container_name: nginx
 external_links:
  - node1:node1
  - node2:node2
  - node3:node3
 volumes:
  - ~/Data/docker/mount/nginx/config/nginx.conf/default.conf:/etc/nginx/nginx.conf:ro
 ports:
  - 1234:1234
 restart: always
